# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin.book:
        class: AdminBundle\Entity\BookAdmin
        arguments: [~, AdminBundle\Entity\Book, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Content', label: Book }

    admin.category:
        class: AdminBundle\Entity\CategoryAdmin
        arguments: [~, AdminBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Content', label: Category }

    admin.quotation:
        class: AdminBundle\Entity\QuotationAdmin
        arguments: [~, AdminBundle\Entity\Quotation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Content', label: Quotation }